"""signals

Revision ID: 24bedaea9eb0
Revises: b25d1b567830
Create Date: 2026-06-02 21:55:07.579274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bedaea9eb0'
down_revision: Union[str, Sequence[str], None] = 'b25d1b567830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('tx_type', sa.String(length=4), nullable=False),
    sa.Column('tx_date', sa.String(length=10), nullable=False),
    sa.Column('disclosed_date', sa.String(length=10), nullable=False),
    sa.Column('amount_range', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=300), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    # ### end Alembic commands ###
