"""bots and positions

Revision ID: b25d1b567830
Revises: 1974b81ea46c
Create Date: 2026-06-02 20:48:29.975118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25d1b567830'
down_revision: Union[str, Sequence[str], None] = '1974b81ea46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('schedule_cadence_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop_floor', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('triggered_rungs', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('bots')
    # ### end Alembic commands ###
